services:

  fdpindexproxy:
    image: markw/fdp-tools:0.0.1
    container_name: fdptools
    ports:
      - 10000:4567
    environment:
      - FDP_INDEX=https://tools.ostrails.eu/repositories/fdpindex-fdp
    restart: always

